name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: casita-family-prod
  REGION: us-central1
  SERVICE: casita-family-app

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Note: Replace this with your actual Workload Identity Provider ID
          workload_identity_provider: 'projects/111047255377/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'casita-deployer@casita-family-prod.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./
          env_vars: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
